//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeServiceWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeAngular
    {
        public string empID { get; set; }
        public string names { get; set; }
        public string gender { get; set; }
        public Nullable<decimal> annualsalary { get; set; }
        public string dateofbirth { get; set; }
        public string locations { get; set; }
    }
}
